hospital/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pacientes/' , include('pacientes.urls')),
    path('usuarios/' , include('usuarios.urls')),
    path('articulos/' , include('articulos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pacientes/urls.py
from django.urls import path
from .views import Lista, Nuevo, Eliminar, Editar, buscar_municipio,ListaPdf,Grafica,PacientePdf

app_name = 'pacientes'

urlpatterns = [
    path('lista/', Lista.as_view(), name='lista'),
    path('nuevo/', Nuevo.as_view(), name='nuevo'),
    path('editar/<int:pk>', Editar.as_view(), name='editar'),
    path('eliminar/<int:pk>', Eliminar.as_view(), name='eliminar'),
    path('busca-municipio/', buscar_municipio, name='buscar_municipio'),
    path('pdf/', ListaPdf.as_view(), name='pdf'),
    path('pdf/<int:pk>', PacientePdf.as_view(), name='pdf_paciente'),
    path('graficas/', Grafica.as_view(), name='pacientes_graficas'),
]

pacientes/models.py
from django.db import models
from .validators import nns_validador


class Estado(models.Model):
    nombre = models.CharField('Nombre del estado',max_length=120)
    def __str__(self):
        return self.nombre
    

class Municipio(models.Model):
    nombre = models.CharField('Nombre del municipio',max_length=120)
    estado = models.ForeignKey(Estado, verbose_name="Estado", on_delete=models.CASCADE)
    def __str__(self):
        return self.nombre


class Paciente(models.Model):
    TIPO_SANGRE =  [
        ('A+', 'A positivo'),
        ('A-', 'A negativo'),
        ('O+', 'O positivo'),
    ]
    nombre = models.CharField(max_length=60)
    primerApellido = models.CharField('Apellido paterno',max_length=60)
    segundoApellido = models.CharField('Apellido materno', max_length=60, null=True, blank=True)
    numero_ss = models.CharField('Número de Seguro Social',max_length=20, validators=[nns_validador])
    fecha_nac = models.DateField('Fecha de nacimiento')
    tipo_sangre = models.CharField('Tipo de sangre', max_length=3, choices=TIPO_SANGRE)
    municipio = models.ForeignKey(Municipio, verbose_name='Municipio', on_delete=models.SET_NULL, null=True)
    estado = models.ForeignKey(Estado, verbose_name='Estado', on_delete=models.SET_NULL, null=True)


    def __str__(self):
        return self.nombre + ' ' + self.primerApellido
    

pacientes/forms.py
from .models import Paciente
from django.forms import ModelForm, TextInput, Select, DateInput


class PacienteForm(ModelForm):

    class Meta:
        model = Paciente
        fields = ('nombre','primerApellido','segundoApellido',
            'numero_ss','fecha_nac','tipo_sangre','estado','municipio')

        widgets = {
                'nombre':TextInput(attrs={'class':'form-control'}),
                'primerApellido':TextInput(attrs={'class':'form-control'}),
                'segundoApellido':TextInput(attrs={'class':'form-control'}),
                'numero_ss':TextInput(attrs={'class':'form-control'}),
                'fecha_nac':DateInput(attrs={'class':'form-control'}),
                'tipo_sangre':Select(attrs={'class':'form-control'}),
                'estado':Select(attrs={'class':'form-control'}),
                'municipio':Select(attrs={'class':'form-control'}),
        }

pacientes/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Paciente, Municipio, Estado
from .forms import PacienteForm
from django.urls import reverse_lazy
from django.http import JsonResponse
from django_weasyprint import WeasyTemplateResponseMixin
from django.conf import settings
from django.views.generic import TemplateView
from django.db.models import Count
from datetime import date
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin, AccessMixin


class Lista(LoginRequiredMixin,PermissionRequiredMixin,ListView):
    permission_required = 'usuarios.permisos_administradoress'
    paginate_by = 5
    model = Paciente

class Nuevo(LoginRequiredMixin,CreateView):
    model = Paciente
    form_class = PacienteForm
    
    success_url = reverse_lazy('pacientes:lista')

class Editar(LoginRequiredMixin,UpdateView):
    model = Paciente
    form_class = PacienteForm
    extra_context = {'editar':True}

    success_url = reverse_lazy('pacientes:lista')

class Eliminar(LoginRequiredMixin,DeleteView):
    model = Paciente
    success_url = reverse_lazy('pacientes:lista')


def buscar_municipio(request):
    id_estado = request.POST.get('id',None)
    if id_estado:
        municipios = Municipio.objects.filter(estado_id=id_estado)
        data = [{'id':mun.id,'nombre':mun.nombre} for mun in  municipios]
        return JsonResponse(data, safe=False)
    return JsonResponse({'error':'Parámetro inválido'}, safe=False)


class VistaPdf(LoginRequiredMixin,ListView):
    model = Paciente
    template_name = 'pacientes/paciente_pdf.html'
    
class ListaPdf(WeasyTemplateResponseMixin, VistaPdf):
    passpdf_stylesheets = [ settings.STATICFILES_DIRS[0] + 'dist/css/misEstilos.css']
    pdf_attachment = False
    pdf_filename = 'Pacientes.pdf'

class VistaPdfPaciente(ListView):
    model = Paciente
    template_name = 'pacientes/paciente_pdf_individual.html'

    def get_queryset(self, **kwargs):
        pk = self.kwargs.get('pk',None)
        queryset = Paciente.objects.filter( id = pk)
        print(queryset)
        return queryset
    

class PacientePdf(WeasyTemplateResponseMixin,VistaPdfPaciente):
    passpdf_stylesheets = [ settings.STATICFILES_DIRS[0] + 'dist/css/misEstilos.css' ]
    pdf_attachment = False
    pdf_filname = 'Paciente.pdf'


class Grafica(LoginRequiredMixin,TemplateView):
    template_name = 'pacientes/grafica.html'
    pacientes_tipo = Paciente.objects.all().values('tipo_sangre').annotate(cuantos=Count('tipo_sangre'))
    tipos = Paciente.objects.all()

    datos = []
    tipos_de_sangre = []
    cuantos=0
    for tipo in tipos:
        if tipo.tipo_sangre in tipos_de_sangre:
            pass
        else:
            tipos_de_sangre.append(tipo.tipo_sangre)
            pt=pacientes_tipo[cuantos]
            num=pt['cuantos']
            datos.append({'name':tipo.tipo_sangre, 'data':[num]})
        cuantos=cuantos+1

    datos2 = []
    hoy = date.today()
    edades = Paciente.objects.all()
    edades_existentes = []
    ninos1=0
    ninos2=0
    ninos3=0
    adoles=0
    jovenes=0
    adultos1=0
    adultos2=0

    for edad in edades:
        año_paciente=edad.fecha_nac
        fecha=hoy.year - año_paciente.year - ((hoy.month, hoy.day) < (año_paciente.month, año_paciente.day))
        if fecha <= 3:
            ninos1=ninos1+1
        if fecha>3 and fecha<=7:
            ninos2=ninos2+1
        if fecha>7 and fecha<=12:
            ninos3=ninos3+1
        if fecha>12 and fecha<=17:
            adoles=adoles+1
        if fecha>17 and fecha<=29:
            jovenes=jovenes+1
        if fecha>29 and fecha<=49:
            adultos1=adultos1+1
        if fecha>=50:
            adultos2=adultos2+1

    datos2.append({'name':'niños 0-3 años', 'data':[ninos1]})
    datos2.append({'name':'niños 4-7 años', 'data':[ninos2]})
    datos2.append({'name':'niños 8-12 años', 'data':[ninos3]})
    datos2.append({'name':'adolescentes 13-17 años', 'data':[adoles]})
    datos2.append({'name':'jovenes 18-29 años', 'data':[jovenes]})
    datos2.append({'name':'adultos 30-49 años', 'data':[adultos1]})
    datos2.append({'name':'adultos 50 años o más', 'data':[adultos2]})
    extra_context = {'datos':datos,'datos2':datos2}

pacientes/templates/pacientes/grafica.html
{% extends 'base.html' %}

{% block titulo %}
    Gráfica
{% endblock titulo %}

{% block contenido %}
    <div id="grafica" style="min-width: 310px;height: 400px; margin: 0 auto;"></div>
    <script src="https://code.highcharts.com/highcharts.src.js"></script> 
    <script src="https://code.highcharts.com/modules/exporting.js"></script> 
    <script src="https://code.highcharts.com/modules/exporting-data.js"></script> 


    </script>
    <script>
        Highcharts.chart('grafica',{
            lang:{
                downloadCSV: 'Descarga CSV',
                downloadJPEG: 'Descarga imagen JPEG',
                downloadPDF: 'Descarga PDF',
                downloadPNG: 'Descarga imagen PNG',
                downloadSVG: 'Descarga en imagen de vectores',
                viewFullscreen: 'Ver en pantalla completa',
                printChart: 'Imprimir gráfica'
            },
            chart:{
                type: 'column'
            },
            title: {
                text: 'Gráfica de tipo de sangre'
            },
            subtitle: {
                text: 'Cuantos pacientes por tipo de sangre'
            },
            xAxis:{
                categories: ['Tipo']
            },
            yAxis:{
                min:0,
                title:{
                    text: 'Numero de pacientes'
                }
            },
            plotOptions:{
                column:{
                    pointPaddin: 0.2,
                    borderWidth: 0,

                }
            },
            series: {{datos|safe}}
            
        });
    </script>


</script>

<br>
<br>

<div id="grafica2" style="min-width: 310px;height: 400px; margin: 0 auto;"></div>
    <script src="https://code.highcharts.com/highcharts.src.js"></script> 
    <script src="https://code.highcharts.com/modules/exporting.js"></script> 
    <script src="https://code.highcharts.com/modules/exporting-data.js"></script> 
<script>
    Highcharts.chart('grafica2',{
        lang:{
            downloadCSV: 'Descarga CSV',
            downloadJPEG: 'Descarga imagen JPEG',
            downloadPDF: 'Descarga PDF',
            downloadPNG: 'Descarga imagen PNG',
            downloadSVG: 'Descarga en imagen de vectores',
            viewFullscreen: 'Ver en pantalla completa',
            printChart: 'Imprimir gráfica'
        },
        chart:{
            type: 'column'
        },
        title: {
            text: 'Gráfica de edad de pacientes'
        },
        subtitle: {
            text: 'Cuantos pacientes por edad'
        },
        xAxis:{
            categories: ['Edad']
        },
        yAxis:{
            min:0,
            title:{
                text: 'Numero de pacientes'
            }
        },
        plotOptions:{
            column:{
                pointPaddin: 0.2,
                borderWidth: 0,

            }
        },
        series: {{datos2|safe}}
        
    });
</script>
    
{% endblock contenido %}

pacientes/templates/pacientes/paciente_confirm_delete.html
{% extends 'base.html' %}
{% block titulo %}
    Eliminar paciente
{% endblock titulo %}

{% block contenido %}

<form method="post">
    {% csrf_token %}
    <p>Quieres eliminar el paciente "{{ object }}"?</p>
    <input class="btn btn-danger" type="submit" value="Sí, si quiero">
    <a href="{% url 'pacientes:lista' %}" class="btn btn-secondary" >Mejor no</a>
</form>

{% endblock contenido %}

pacientes/templates/pacientes/paciente_form.html
{% extends 'base.html' %}

{% block titulo %}
    Agrega paciente
{% endblock titulo %}

{% block contenido %}
<div class="row">
    <div class="col-md-2"></div> 
    <div class="col-md-8">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">
                    {% if editar %}
                        Modificar paciente
                    {% else %}
                        Nuevo paciente
                    {% endif %}
                </h3>
            </div>
                <form method="post">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <div class="card-footer">
                        <input type="submit" class="btn btn-success" value="{% if editar %}Guardar cambios{% else %}Agregar{% endif %}">
                    </div>
                </form>
            </div>
        </div>
    </div> 
    <div class="col-md-2"></div> 

    {% endblock contenido %}
    
    

pacientes/templates/pacientes/paciente_list.html
{% extends 'base.html' %}

{% block titulo %}Lista de pacientes{% endblock titulo %}

{% block contenido %}
<div class="contenedor">
    <h1>Lista de pacientes</h1>
    <a href="{% url 'pacientes:pdf' %}" class="btn btn-lg bg-success" role="button" aria-pressed="true">Generar PDF</a>
</div>

<p><b>Total de pacientes:</b> {{contador}}</p>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Apellido paterno</th>
            <th>Apellido materno</th>
            <th>Fecha de nacimiento</th>
            <th>No. Seguro social</th>
            <th>Tipo de sangre</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
        {% for paciente in object_list %}
        <tr>
            <td>{{paciente.nombre}}</td>
            <td>{{paciente.primerApellido}}</td>
            <td>{{paciente.segundoApellido}}</td>
            <td>{{paciente.fecha_nac}}</td>
            <td>{{paciente.numero_ss}}</td>
            <td>{{paciente.tipo_sangre}}</td>
            <td>
                <a title="Actualiza paciente" class="btn btn-warning" href="{% url 'pacientes:editar' paciente.id %}">
                    <i class="far fa-edit"></i>
                </a>
                <a title="Elimina paciente" class="btn btn-danger" href="{% url 'pacientes:eliminar' paciente.id %}">
                    <i class="far fa-trash-alt"></i>
                </a>
                <a title="Generar pdf" href="{% url 'pacientes:pdf_paciente' paciente.id %}" class="btn btn-info">
                    <i class="fas fa-file-pdf"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div class="pagination justify-content-center">
    
    <ul class="pagination">

        <li class="page-item ">
            <a href="?page=1" class="page-link">&laquo; Primero</a>
        </li>

        {% for i in page_obj.paginator.page_range %}

            {% if page_obj.number == i  %}
                <li class="page-item active">
                    <a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a>
                </li>

            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}

        {% endfor %}

        <li class="page-item ">
            <a href="?page={{ page_obj.paginator.num_pages }}" class="page-link">Ultimo &raquo;</a>
        </li>

    </ul>
</div>
{% endblock contenido %}
    

pacientes/templates/pacientes/paciente_pdf.html
{% load static %}
<html>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Inria+Sans&display=swap');
        h1{
            color: #00a8cc;
        }
        table{
            background-color: #fff;
            text-align: left;
            width: 90%;
            border-collapse: collapse;
        }
        table th, td{
            text-align: center;
            font-size: 15px;
            font-family: 'Inria Sans', sans-serif;
        }
        table thead{
            background: #1eafed;
            border-bottom: solid 5px #000000 ;
            text-align: center;
            color: #fff;
        }
    
    
    </style>
<body>
    <h1>Hospital Matasanos</h1>
<br>
<h2>Lista de pacientes</h2>
<table>
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Apellido paterno</th>
            <th>Apellido materno</th>
            <th>Fecha de nacimiento</th>
            <th>No. Seguro social</th>
            <th>Tipo de sangre</th>
        </tr>
    </thead>
    <tbody>
        {% for paciente in object_list %}
        <tr>
            <td>{{paciente.nombre}}</td>
            <td>{{paciente.primerApellido}}</td>
            <td>{{paciente.segundoApellido}}</td>
            <td>{{paciente.fecha_nac}}</td>
            <td>{{paciente.numero_ss}}</td>
            <td>{{paciente.tipo_sangre}}</td>
           
        </tr>
        {% endfor %}
    </tbody>
</table>

</body>
</html>

pacientes/templates/pacientes/paciente_pdf_individual.html
{% load static %}
<html>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Inria+Sans&display=swap');
        h1{
            color: #00a8cc;
        }
        table{
            background-color: #fff;
            text-align: left;
            width: 90%;
            border-collapse: collapse;
        }
        table th, td{
            text-align: center;
            font-size: 15px;
            font-family: 'Inria Sans', sans-serif;
        }
        table thead{
            background: #1eafed;
            border-bottom: solid 5px #000000 ;
            text-align: center;
            color: #fff;
        }
    
    
    </style>
<head>
    <title>Detalles del paciente</title>
</head>
<body>
    <h1>Hospital Matasanos</h1>
<br>
<h2>Datos del paciente</h2>
<table>
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Apellido paterno</th>
            <th>Apellido materno</th>
            <th>Fecha de nacimiento</th>
            <th>No. Seguro social</th>
            <th>Tipo de sangre</th>
        </tr>
    </thead>
    <tbody>

        {% for paciente in object_list %}
        <tr>
            <td>{{paciente.nombre}}</td>
            <td>{{paciente.primerApellido}}</td>
            <td>{{paciente.segundoApellido}}</td>
            <td>{{paciente.fecha_nac}}</td>
            <td>{{paciente.numero_ss}}</td>
            <td>{{paciente.tipo_sangre}}</td>
           
        </tr>
        {% endfor %}
    </tbody>
</table>

</body>
</html>