articulos/urls.py
from django.urls import path
from .views import Lista, comprar, confirmaCompra, cancelarCompra, VerCarrito, HistorialVenta, eliminar
from . import views

app_name = 'articulos'

urlpatterns = [
    path('lista/', Lista.as_view(), name='lista'),
    path('comprar/', comprar, name='comprar'),
    path('vercarrito/',VerCarrito.as_view(),name='vercarrito'),
    path('confirmaCompra/<int:pk>',confirmaCompra,name='confirmaCompra'),
    path('cancelarCompra/',cancelarCompra, name='cancelarCompra'),
    path('historialVentas', HistorialVenta.as_view(), name='historialVenta'),
    path('eliminar/<int:pk>', eliminar, name='eliminar'),
]

hospital/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pacientes/' , include('pacientes.urls')),
    path('usuarios/' , include('usuarios.urls')),
    path('articulos/' , include('articulos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articulos/models.py
from django.db import models

class Articulo(models.Model):
    clave = models.CharField("Clave", max_length=30)
    nombre = models.CharField("Articulo", max_length = 150)
    descripcion = models.CharField("Descripcion", max_length = 300, blank=True, null=True)
    imagen = models.ImageField("Imagen", upload_to="articulos")
    precio = models.DecimalField("Precio unitario", max_digits=8, decimal_places=2)
    stock = models.IntegerField("Unidades")
    categoria = models.ForeignKey("articulos.Categoria", verbose_name="Categoria", on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.nombre

class Categoria(models.Model):
    nombre = models.CharField("Categoria",max_length=100)

    def __str__(self):
        return self.nombre


class Venta(models.Model):
    fecha = models.DateField(auto_now_add=True)
    usuario = models.ForeignKey("usuarios.Usuario", verbose_name="Usuario",on_delete=models.DO_NOTHING)
    
    def __str__(self):
        return self.fecha

class DetalleVenta(models.Model):
    articulo = models.ForeignKey("articulos.Articulo", verbose_name="Articulo",on_delete=models.CASCADE)
    venta = models.ForeignKey("articulos.Venta",verbose_name="Venta",on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.articulo.nombre+' '+self.venta.fecha.strftime('%d/%m/%Y')

articulos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin, AccessMixin
from django.views.generic.list import ListView
from django.views.generic import TemplateView, DeleteView
from .models import Articulo, Venta, DetalleVenta
from usuarios.models import Usuario
from django import template
from django.urls import reverse_lazy
from datetime import datetime
from django.contrib import messages


class Lista(LoginRequiredMixin,ListView):
    model = Articulo
    paginate_by = 6

def comprar(request):

    pk = request.POST.get('id')
    cantidad = int(request.POST.get('cantidad'))

    articulo = get_object_or_404(Articulo, pk=pk)
    
    if articulo.stock > 0:

        #articulo.stock = articulo.stock - cantidad

        articulo.save()

        id = str(pk)
        request.session['total'] = request.session['total'] + float(articulo.precio) * cantidad
        request.session['cuantos'] = request.session['cuantos'] + cantidad

        if( id in request.session['articulos']):
            request.session['articulos'][id]['cantidad'] = request.session['articulos'][id]['cantidad'] + cantidad
        else:
            request.session['articulos'][id] = {'nombre':articulo.nombre,'precio':float(articulo.precio),'cantidad': cantidad,}

            print(request.session['articulos'])

    return redirect('articulos:lista')


class VerCarrito(LoginRequiredMixin,ListView):
    model = Articulo
    template_name = 'articulos/venta_list.html'

    def get_queryset(self):

        id_articulos = list(self.request.session['articulos'].keys())

        carrito = list()

        for id in id_articulos:
            articulo = Articulo.objects.get(pk = id)
            cantidad = self.request.session['articulos'][id]['cantidad']

            tempo = (articulo,cantidad)
            print(tempo)

            carrito.append(tempo)
            

        return carrito

def confirmaCompra(request, pk):

    id_articulos = list(request.session.get('articulos').keys())

    print(id_articulos)
    print(Usuario.objects.get( pk = pk))

    venta = Venta.objects.create(fecha = datetime.now() , usuario = Usuario.objects.get( pk = pk))
    venta.save()


    for id in id_articulos:

        articulo = Articulo.objects.get(pk = id)
        cantidad = request.session['articulos'][id]['cantidad']
        articulo.stock = articulo.stock - cantidad
        articulo.save()

        #detalle = DetalleVenta(articulo.id, venta.id)
        detalle = DetalleVenta.objects.create(articulo = articulo, venta = venta)

        detalle.save()

        
    messages.success(request, 'Felicidades por tu compra!!')
    
    request.session['articulos'] = {}
    request.session['total'] = 0
    request.session['cuantos'] = 0  

    
    return redirect('articulos:lista')


def cancelarCompra(request):
    
    request.session['articulos'] = {}
    request.session['total'] = 0
    request.session['cuantos'] = 0  

    messages.error(request, 'Tu compra ha sido cancelada')

    return redirect('articulos:lista')


class HistorialVenta(LoginRequiredMixin,ListView):
    model = DetalleVenta


def eliminar(request, pk):
    val = int(pk)
    obj = get_object_or_404(Articulo, id = val)
    print(obj)
    obj.delete()
    return redirect('articulos:lista')

articulos/templates/articulos/articulo_list.html
<style>
    #presio{
        color: red;
    }
    #titulo{
        color: black;
        font-weight: bold;
    }
</style>


{% extends 'base.html' %}

{% block titulo %}Lista de articulos{% endblock titulo %}

{% block contenido %}
<div class="contenedor">
    <h1>Lista de articulos</h1>
</div>

{% include './messages.html' %}

<div class="album py-5 bg-ligth">
    <div class="container">
        <div class="row">

        {% for articulo in object_list %}
            <div class="col-md-4">

                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="{{  MEDIA_URL }}/{{ articulo.imagen }}" alt="Card image cap">
                    <div class="card-body">
                        <h5 id="titulo">{{ articulo.nombre}}</h5>
                      <p class="card-text">{{ articulo.descripcion }}</p>
                    </div>
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item">Stock: {{articulo.stock}}</li>
                      <li class="list-group-item">Precio: <h5 id="presio">{{ articulo.precio }}</h5> </li>
                      
                      <li class="list-group-item"> Cantidad:
                            <div class="form-group">

                                <form action="{% url 'articulos:comprar' %}" method="POST">
                                    <input type="text" name="id" value="{{ articulo.id }}" hidden > 
                                    {% csrf_token %}
                                    <select class="form-control" name="cantidad" >
                                        {% with ''|center:articulo.stock as range %}
                                        {% for _ in range %}
                                            <option name="opcion">{{ forloop.counter }}</option>
                                        {% endfor %}.0
                                        {% endwith %}
                                    </select>

                                    <div class="card-body text-center">
                        
                                        {% if articulo.stock > 0 %}
                                            <div class="btn btn-success">
                                                <i class="fas fa-cart-plus">
                                                    <input class="btn" type="submit" value="Agregar al carrito">
                                                </i>
                                            </div>
                                        {% else %}
                                            
                                            <i class="fas fa-times-circle"></i> Sin existencias
                                            
                                        {% endif %}
                                            
                                    </div>

                                </form>
                                
                            </div>
                      </li>
                      
                      {% if perms.usuarios.permiso_administradoress %}
                        <li class="list-group-item text-center">
                            <a class="btn btn-danger" href="javascript:eliminarModal( '{% url 'articulos:eliminar' articulo.id %}' )">
                                <i class="far fa-trash-alt"> Eliminar articulo</i>
                            </a>
                        </li>
                      {% endif %}
                          
                    </ul>
                    
                  </div>

            </div>
        {% endfor %}

        </div>
    </div>
</div>

<!-- Button trigger modal -->
<button hidden id="btnModal" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Launch demo modal
  </button>
  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Elimina articulo</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          ¿Estas seguro de eliminar el articulo? 
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal"><a class="btn btn-secondary" href=""> Cancelar</a></button>
          <button type="button" class="btn btn-danger"><a class="btn btn-danger" id="confirmaEliminacion" href=""> Eliminar</a></button>
        </div>
      </div>
    </div>
  </div>
    

<div class="pagination justify-content-center">
    
    <ul class="pagination">

        <li class="page-item ">
            <a href="?page=1" class="page-link">&laquo; Primero</a>
        </li>

        {% for i in page_obj.paginator.page_range %}

            {% if page_obj.number == i  %}
                <li class="page-item active">
                    <a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a>
                </li>

            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}

        {% endfor %}

        <li class="page-item ">
            <a href="?page={{ page_obj.paginator.num_pages }}" class="page-link">Ultimo &raquo;</a>
        </li>

    </ul>
</div>

<script>
    setTimeout(function(){
        if($('#msg').length > 0){
            $('#msg').remove()
        }
    },4000);

    function eliminarModal(url) {
        document.querySelector("#confirmaEliminacion").setAttribute('href',url);
        document.querySelector("#btnModal").click()
    }


</script>



{% endblock contenido %}

articulos/templates/articulos/detalleventa_list.html
{% extends 'base.html' %}

{% block contenido %}
<div class="contenedor">
    <h1>Historial Ventas</h1>
    
</div>

<div class="table-responsive">


    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Detalle</th>
                
            </tr>
        </thead>
        <tbody>
            {% for ven in object_list %}
            <tr>
                <td>{{ ven }}</td>
            </tr>
            {% endfor %}
           
        </tbody>
    </table>

</div>



{% endblock contenido %}
    

articulos/templates/articulos/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" id="msg">
    {{ message }}
  </div>
{% endfor %}

articulos/templates/articulos/venta_list.html
{% extends 'base.html' %}

{% block titulo %}Lista de articulos{% endblock titulo %}

{% block contenido %}
<div class="contenedor">
    <h1>Tu carrito</h1>
    
</div>



<div class="container">
       <div class="row">
           <div class="col-10">
                <a href=" {% url 'articulos:lista' %}" class="btn btn-dark"><i class="fas fa-long-arrow-alt-left"></i> Articulos </a>
            
                <a href="{% url 'articulos:confirmaCompra' user.pk %}" class="btn btn-success"> <i class="fab fa-paypal"></i> Comprar</a>
           </div>

           <div class="col-2">
                <a href="{% url 'articulos:cancelarCompra' %}" class="btn btn-light"><i class="fas fa-ban"></i>  Cancelar</a>
           </div>
            
        
       </div>
</div>
<div class="table-responsive">


    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Imagen</th>
                <th>Nombre</th>
                <th>Descripcion</th>
                <th>Cantidad</th>
                <th>Presio</th>
                
            </tr>
        </thead>
        <tbody>
            {% for valor in object_list %}
            <tr>
                <td><img src="{{  MEDIA_URL }}/{{ valor.0.imagen }}" ></td>
                <td>{{ valor.0.nombre }}</td>
                <td>{{ valor.0.descripcion }}</td>
                <td>{{ valor.1 }}</td>
                <td>{{ valor.0.precio }}</td>
            </tr>
            {% endfor %}
            <tr>
                <td scope="row" colspan="5" class="table-dark">Total: ${{ request.session.total|floatformat:2 }} mx</td>
            </tr>
        </tbody>
    </table>

</div>


<a href="{% url 'articulos:confirmaCompra' user.pk %}" class="btn btn-success btn-lg btn-block">Comprar ahora</a>


{% endblock contenido %}
    