hospital/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pacientes/' , include('pacientes.urls')),
    path('usuarios/' , include('usuarios.urls')),
    path('articulos/' , include('articulos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from .views import Login, Nuevo, Perfil, Lista, Permisos, addAdmin, deleteAdmin, addUser, deleteUser
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('nuevo/', Nuevo.as_view(), name='nuevo'),
    path('perfil/', Perfil.as_view(), name='perfil'),
    path('activar/<slug:uidb64>/<slug:token>', views.ActivarCuenta.as_view(), name ='activar'),
    path('lista/',Lista.as_view(), name='lista'),
    path('permisos/<int:pk>',Permisos.as_view(),name='permisos'),
    path('addAdministrador/<int:pk>',addAdmin, name='nadmin'),
    path('deleteAdministrador/<int:pk>',deleteAdmin,name='deleteAdmin'),
    path('addUsuario/<int:pk>',addUser,name='addUser'),
    path('deleteUsuario/<int:pk>',deleteUser,name='deleteUser'),
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
from .validators import rfc_validador, foto_validador


class Usuario(User):
    rfc = models.CharField('R.F.C.', max_length=13, validators=[rfc_validador])
    foto = models.ImageField('Foto', upload_to='perfil', blank=True, null=True, validators=[foto_validador])

    def __str__(self):
        return self.username
    

usuarios/forms.py
from django.forms import (ModelForm, PasswordInput, 
                CharField, TextInput, ValidationError)
from .models import Usuario


class UsuarioForm(ModelForm):
    password = CharField(widget=PasswordInput(
        attrs={'placeholder':'Escribe contraseña','class':'form-control'}), 
        label="Contraseña"
    )
    password_re = CharField(widget=PasswordInput(
        attrs={'placeholder':'Repite contraseña','class':'form-control'}), 
        label="Repita contraseña"
    )
    
    class Meta:
        model = Usuario
        fields = ('first_name','last_name','email','username','password','password_re')

        widgets = {
                'first_name':TextInput(attrs={'class':'form-control','placeholder':'Escribe tu nombre...'}),
                'email':TextInput(attrs={'class':'form-control','placeholder':'Escribe tu e-mail...'}),
                'last_name':TextInput(attrs={'class':'form-control','placeholder':'Escribe tus apellidos'}),
                'username':TextInput(attrs={'class':'form-control','placeholder':'Esscribe tu nombre de usuario'}),
        }

    def save(self, commit=True):
        user = super(UsuarioForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    def clean_password(self,*args, **kwargs):
        if self.data['password'] != self.data['password_re']:
            raise ValidationError('Las contraseñas son diferentes')
        return self.data['password']


class PerfilForm(ModelForm):
    class Meta:
        model = Usuario
        fields = ('first_name','last_name','email','rfc','foto')

usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import TemplateView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User, Group, Permission
from .forms import UsuarioForm, PerfilForm
from .models import Usuario
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import EmailMessage
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.encoding import force_bytes, force_text
from .token import token_activacion
from django.core.mail import send_mail
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin, AccessMixin
from django.views.generic.list import ListView
from django.contrib import messages



class Login(LoginView):
    template_name = 'login.html'
    form_class = AuthenticationForm

    def get_success_url(self):

        self.request.session['cuantos'] = 0
        self.request.session['total'] = 0.0
        self.request.session['articulos'] = {}

        return super().get_success_url()


class Lista(LoginRequiredMixin,PermissionRequiredMixin,ListView):
    permission_required = 'usuarios.permiso_gestion_permisos'
    model = Usuario
    template_name = 'usuario_list.html'
    
    def has_group(usuario,nombre_grupo):
        return usuario.groups.filter(name=nombre_grupo).exists() 

def addAdmin(request, *args, **kwargs):
    id_user = kwargs['pk']
    usr = Usuario.objects.get(pk = id_user)
    grupos = usr.groups.all()
    print(grupos)


    if grupos.filter(name='administradores').exists():
        messages.error(request, 'El usuario {} ya existe en el grupo administradores'.format(usr.username))
    else:
        usr.groups.add(Group.objects.get(id=10))
        messages.success(request, 'El usuario {} se agrego a el grupo de administradores'.format(usr.username))
        
    return redirect('usuarios:lista')


def deleteAdmin(request, *args, **kwargs):
    id_user = kwargs['pk']
    usr = Usuario.objects.get(pk = id_user)
    grupos = usr.groups.all()
    print(grupos)


    if grupos.filter(name='administradores').exists():

        if(len(grupos)) == 1:
            messages.error(request,'El usuario {} debe de pertenecer al menos a un grupo'.format(usr.username))
        else:
            usr.groups.remove(Group.objects.get(id=10))
            messages.success(request,'Se elimino {} el usuario del grupo'.format(usr.username))
    else:
        messages.error(request,'El usuario {} no esta en el grupo de administracion'.format(usr.username))
    return redirect('usuarios:lista')

def addUser(request, *args, **kwargs):
    id_user = kwargs['pk']
    usr = Usuario.objects.get(pk = id_user)
    grupos = usr.groups.all()
    print(grupos)


    if grupos.filter(name='usuarios').exists():
        messages.error(request, 'El usuario {} ya existe en el grupo usuarios'.format(usr.username))
    else:
        usr.groups.add(Group.objects.get(id=12))
        messages.success(request, 'El usuario {} se agrego a el grupo de usuarios'.format(usr.username))
        
    return redirect('usuarios:lista')


def deleteUser(request, *args, **kwargs):
    id_user = kwargs['pk']
    usr = Usuario.objects.get(pk = id_user)
    grupos = usr.groups.all()
    print(grupos)

    if grupos.filter(name='usuarios').exists():

        if(len(grupos)) == 1:
            messages.error(request,'El usuario {} debe de pertenecer al menos a un grupo'.format(usr.username))
        else:
            usr.groups.remove(Group.objects.get(id=12))
            messages.success(request,'Se elimino {} el usuario del grupo usuarios'.format(usr.username))
    else:
        messages.error(request,'El usuario {} no esta en el grupo de usuarios'.format(usr.username))
    return redirect('usuarios:lista')

class Nuevo(CreateView):
    template_name = 'nuevo.html'
    model = Usuario
    form_class = UsuarioForm
    

    def form_valid(self, form):

        user = form.save(commit=False)
        user.is_active = False
        user.save()

        dominio = get_current_site(self.request)
        mensaje = render_to_string('confirmar_cuenta.html',
            {
                'user': user,
                'dominio': dominio,
                'uid': urlsafe_base64_encode(force_bytes(user.id)),
                'token': token_activacion.make_token(user)
            }
        )

        email = EmailMessage(
            'Hospital mata sanos | Activa cuenta',
            mensaje,
            to=[user.email]
        )
        email.content_subtype = "html"
        email.send()
        mensaje = 'Verifica tu cuenta en tu correo electronico'
        return render(self.request,'login.html', {'mensaje':mensaje})
    #success_url = reverse_lazy('usuarios:login')
        

class ActivarCuenta(TemplateView):
    
    def get(self, request, *args, **kwargs):
        #context = self.get_context_data(**kwargs)
        try:
            uid = urlsafe_base64_decode(force_text(kwargs['uidb64']))
            token = kwargs['token']
            user = User.objects.get(pk=uid)
        except(TypeError, ValueError, User.DoesNotExist):
            user = None
        
        if user is not None and token_activacion.check_token(user, token):
            user.is_active = True
            user.save()
            messages.success(self.request, 'Cuenta activada, ingresa datos')
        else:
            messages.error(self.request, 'Token invalido, contacta con el administrador')

        return redirect('usuarios:lista')
        



class Perfil(SuccessMessageMixin, UpdateView):
    template_name = 'perfil.html'
    model = Usuario
    form_class = PerfilForm
    success_message = "El usuario %(first_name)s se actualizó con éxito"
    success_url = reverse_lazy('usuarios:perfil')

    def get_object(self, queryset=None):
        pk = self.request.user.pk
        obj = Usuario.objects.get(pk = pk)
        return obj

    """def get_success_url(self):
        pk = self.kwargs.get(self.pk_url_kwarg)
        url = reverse_lazy('usuarios:perfil', kwargs={'pk': pk})
        return url"""

class Permisos(LoginRequiredMixin,PermissionRequiredMixin, ListView):
    permission_required = 'usuarios.permiso_gestion_permisos'
    model = Usuario
    template_name = 'permisos.html'
    success_url = reverse_lazy('usuarios:lista')

    
    def get_queryset(self, **kwargs):
        pk = self.kwargs.get('pk',None)
        usr = Usuario.objects.get( id = pk)
        queryset = [(x.name) for x in Permission.objects.filter(user=usr)]
        print(queryset)
        return queryset
    

    

usuarios/templates/confirmar_cuenta.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmar cuenta</title>
</head>
<body>
    <div>
        <h3>Validar cuenta</h3>
        <br>
        <p>
            Hola <b>{{user.username}}</b>
        </p>
        <br>
        <p>
            Para completar tu registro en <b>Hospital MataSanos</b> debes acceder en el siguiente enlace 
        </p>
        <br>
        <p><a href="http://{{dominio}}{% url 'usuarios:activar' uidb64=uid token=token %}">Activar cuenta</a></p>
        <br>
        <p>Saludos</p>

    </div>
</body>
</html>

usuarios/templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Login Hospital</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <!-- <link rel="stylesheet" href="{% static 'https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css' %}"> -->
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="../../index2.html"><b>Admin</b>LTE</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Iniciar sesión</p>

      {% if form.errors %}
          <div class="alert alert-warning">
            Datos no válidos, verifica tu información
          </div>
      {% endif %}

      {% if messages %}
        {% for men in messages %}
          <div class="alert alert-{% if men.tags == 'error' %}warning {% else %}success{% endif %}">
            {{men}}
          </div>
        {% endfor %}
      {% endif %}
      
      <form method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
          <input required type="text" name="username" class="form-control" placeholder="Nombre de usuario">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input required type="password" name="password" class="form-control" placeholder="Contraseña">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember">
              <label for="remember">
                Rercordar usuario
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Ingresar</button>
          </div>
          <!-- /.col -->
        </div>
        <input type="hidden" name="next" value="{{next}}">
      </form>

    
      <p class="mb-1">
        <a href="forgot-password.html">Olvide mi contraseña</a>
      </p>
      <p class="mb-0">
        <a href="{% url 'usuarios:nuevo' %}" class="text-center">Registrar</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>

</body>
</html>

usuarios/templates/nuevo.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Registro Hospital</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition register-page">
<div class="register-box">
  <div class="register-logo">
    <a href="../../index2.html"><b>Hospital Matasanos</a>
  </div>

  <div class="card">
    <div class="card-body register-card-body">
      <p class="login-box-msg">Registro de usuarios</p>

      <form method="post">
          {% csrf_token %}
        {{form.as_p}}
        <div class="row">
            <div class="col-8">
              <div class="icheck-primary">
                <input type="checkbox" id="agreeTerms" name="terms" value="agree">
                <label for="agreeTerms">
                <a href="">Estoy de acuerdo con los terminos</a>
                </label>
              </div>
            </div>
            <!-- /.col -->
            <div class="col-4">
              <button type="submit" class="btn btn-primary btn-block">Registrar</button>
            </div>
            <!-- /.col -->
          </div>
      </form>

      <a href="{% url 'usuarios:login' %}" class="text-center">Ya tengo una cuenta</a>
    </div>
    <!-- /.form-box -->
  </div><!-- /.card -->
</div>
<!-- /.register-box -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
</body>
</html>

usuarios/templates/perfil.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
    Modifica perfil de usuario
{% endblock titulo %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/toastr/toastr.min.css' %}">
{% endblock css %}

{% block contenido %}
<div class="row">
    <div class="col-md-2"></div> 
    <div class="col-md-8">
        {{mensaje}}
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">
                   Actualiza perfil
                </h3>
            </div>
                
                <form method="post" enctype="multipart/form-data">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <div class="card-footer">
                        <input type="submit" class="btn btn-success" value="Actualizar datos">
                    </div>
                </form>
            </div>
        </div>
    </div> 
    <div class="col-md-2"></div> 

    {% endblock contenido %}
    
    
    {% block scripts %}
        
      
        {% if messages %}
        <script src="{% static 'plugins/sweetalert2/sweetalert2.min.js' %}"></script>
        <!-- Toastr -->
        <script src="{% static 'plugins/toastr/toastr.min.js' %}"></script>
            <script type="text/javascript">
                var mensaje = '';
                {% for message in messages %}
                    mensaje += '{{message}}';
                {% endfor %}
                
                    const Toast = Swal.mixin({
                        toast: true,
                        position: 'top-end',
                        showConfirmButton: false,
                        timer: 3000
                    });
            
                    Toast.fire({
                        type: 'success',
                        title: mensaje
                    });
               
            </script>
        {% endif %}
    {% endblock scripts %}
        
    

usuarios/templates/permisos.html
{% extends 'base.html' %}

{% block titulo %}Lista permisos{% endblock titulo %}

{% block contenido %}
<div class="contenedor">
    <h1>Permisos</h1>
</div>

<div class="container">
    <div class="row">
      <div class="col">
        <h4>Todos los permisos</h4>
        <select select class="custom-select" multiple>
            {% for permisosTotales in total_permisos %}
                <option value="">{{   permisosTotales  }}</option>
            {% endfor %}
        </select>
      </div>
      <div class="col">
        <h4>Permisos del usuario</h4>
        <select class="custom-select" multiple>
            
            {% for permisosUsuario in object_list %}
                <option value="">{{permisosUsuario}}</option>
            {% endfor %}
                
        </select>
      </div>
    </div>
</div>

<br>
<button type="button" class="btn btn-success btn-lg btn-block">Agrear permiso</button>
<button type="button" class="btn btn-danger btn-lg btn-block">Eliminar permiso</button>






{% endblock contenido %}

usuarios/templates/usuario_list.html
{% extends 'base.html' %}

{% block titulo %}Lista permisos{% endblock titulo %}

{% block contenido %}
<div class="contenedor">
    <h1>Lista de usuarios</h1>
</div>


{% include './messages.html' %}

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nombre de usuario</th>
            <th>Correo</th>
            <th>Administrador</th>
            <th>Usuario</th>
            <th>Permisos</th>
        </tr>
    </thead>
    <tbody>
        {% for usuario in object_list %}
        <tr>
            <td>{{usuario.username}}</td>
            <td>{{usuario.email}}</td>
            <td>
                <a title="Actualiza paciente" class="btn btn-success" href="{% url 'usuarios:nadmin' usuario.id %}">
                    <i class="fas fa-check"></i>
                </a>

                <a title="Actualiza paciente" class="btn btn-danger" href="{% url 'usuarios:deleteAdmin' usuario.id %}">
                    <i class="fas fa-times"></i>
                </a>
            </td>
            <td>
                <a title="Actualiza paciente" class="btn btn-success" href="{% url 'usuarios:addUser' usuario.id %}">
                    <i class="fas fa-check"></i>
                </a>

                <a title="Actualiza paciente" class="btn btn-danger" href="{% url 'usuarios:deleteUser' usuario.id %}">
                    <i class="fas fa-times"></i>
                </a>
            </td>
            <td><a class="btn btn-dark" href="{% url 'usuarios:permisos' usuario.id %}" role="button">Cambiar Permisos</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<script>
    setTimeout(function(){
        if($('#msg').length > 0){
            $('#msg').remove()
        }
    },4000)
</script>


{% endblock contenido %}

    